name: "Docker image build"
description: "Build a docker image and publish it to the repository"
inputs:
  username:
    description: Username for authenticating to the Docker registry
    required: true
  password:
    description: Password or personal access token for authenticating the Docker registry
    required: true
  image-name:
    description: The name of the image to be bublished
    required: true
  context:
    description: Build's context is the set of files located in the specified PATH or URL
    required: true
  dockerfile:
    description: Path to the Dockerfile.
    required: true
  push:
    description: Push the image to the package repository
    required: false
    default: true
outputs:
  sha-tag:
    value: sha-${{ steps.get_sha.outputs.sha_short }}
    description: The SHA tag of the image
runs:
  using: "composite"
  steps:
    - name: Get SHA
      id: get_sha
      shell: sh {0}
      run: |
        git config --global --add safe.directory $(pwd)
        echo "sha_short=$(set -e;git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ghcr.io/${{ github.repository }}/${{ inputs.image-name }}
        tags: |
          type=raw,value=latest
          type=semver,pattern={{version}}
          type=sha
    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        push: ${{ inputs.push }}
        tags: ${{ steps.meta.outputs.tags }}
        cache-from: type=registry,ref=ghcr.io/${{ github.repository }}/${{ inputs.image-name }}:latest
        cache-to: type=inline
