# Recommended: Specify your app ID *OR* your base resource path for more robust icon loading
# app_id = "com.my.app"
# base_resource_path = "/com/my/app/"

# List of icon names you found (shipped with this crate)
# Note: the file ending `-symbolic.svg` isn't part of the icon name.
icons = [
    ###
    ### mxl plyr
    ###
    "menu",
    "dock-left",
    "play-large",
    "pause-large",
    "stop-large",
    "arrow-previous-filled",
    "arrow-next-filled",
    "step-over",
    "playback-error",

    ###
    ### mxl-relm4-components
    ###
    "warning",

    ###
    ### mxl-licensing
    ###
    "arrow-clockwise-regular",
    "check-round-outline",
    "left-large",
    "right-large",
    "user-trash",
    "save-regular",
    # "warning",
    "copy",

    ###
    ### mxl-investigator
    ###
    # "left-large",
    # "right-large",

    ###
    ### player-components
    ###
    # "play-large",
    "small-x",
    "plus",
    # "warning",
    "arrow-repeat-all-off-filled",
    "arrow-repeat-all-filled",
    "video-clip-multiple-regular",
]

# Optional: Specify a folder containing your own SVG icons
# icon_folder = "my_svg_icons"
